class_name Constant
extends Object

# Prompt
const DEFAULT_PROMPT = "You are a helpful assistant"
const GOSUB_TRANSLATE = """请你扮演专业翻译员的角色。将各种语言的输入翻译为中文。翻译时追求自然流畅、贴近原文。

**注意事项**：
- 严格保留每行开头的时间格式，示例"[1.44->3.18]"。
- 翻译结果不要换行，不要省略标点符号。
- 不要输出任何与翻译结果无关的注释内容。

**翻译示例**：
输入：
[00:03:44.060->00:03:45.720]So let's open up the project,

输出：
[00:03:44.060->00:03:45.720]让我们打开项目，
"""

const ASS_TEMPLATE = """[Script Info]
; Script generated by Gosub
; https://github.com/1e0nhardt/Gosub
ScriptType: v4.00+
ScaledBorderAndShadow: Yes
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: EN,Resource Han Rounded CN Regular,40,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,2,1,2,5,5,15,1
Style: ZH,Resource Han Rounded CN Regular,64,&H00FFFFFF,&HF00000FF,&H00000000,&H32000000,-1,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

const DEFAULT_SETTINGS := {
    "video": {
        "download": {
            "proxy": {
                "type": TYPE_STRING,
                "data": "",
                "tooltip": "Proxy for downloading video."
            },
        },
        "render": {
            "bit_rate": {
                "type": TYPE_STRING,
                "data": "6M",
                "tooltip": "Bit rate for video encoding."
            },
        },
    },
    "transcribe": {
        "whisper.cpp": {
            "use_gpu": {
                "data": false,
                "tooltip": "Whether to use GPU for transcribe.",
                "type": TYPE_BOOL
            },
            "model_path": {
                "data": "",
                "hint_string": "path",
                "tooltip": "Path to the model file.",
                "type": TYPE_STRING
            },
            "smart_split": {
                "data": false,
                "tooltip": "Whether to use smart split. i.e transcribe with -ml 1, split with full stop.",
                "type": TYPE_BOOL
            },
            "smart_split_threshold": {
                "data": 5.0,
                "tooltip": "Long sentence threshold for smart split.",
                "hint_string": "4.0, 20.0, 0.1, s",
                "type": TYPE_FLOAT
            },
        }
    },
    "llm": {
        "common": {
            "clips_per_chat": {
                "type": TYPE_INT,
                "data": 16,
                "tooltip": "Number of clips per chat.",
            },
            "prompt": {
                "translate": {
                    "type": TYPE_STRING,
                    "data": GOSUB_TRANSLATE,
                    "hint_string": "multiline",
                    "tooltip": "Translate prompt for DeepSeek.",
                },
                "chat": {
                    "type": TYPE_STRING,
                    "data": DEFAULT_PROMPT,
                    "hint_string": "multiline",
                    "tooltip": "Chat prompt for DeepSeek.",
                }
            },
        },
        "deepseek": {
            "api_key": {
                "type": TYPE_STRING,
                "data": "",
                "tooltip": "API key for DeepSeek.",
            },
        },
    },
    "subtitle": {
        "ass": {
            "template": {
                "type": TYPE_STRING,
                "data": ASS_TEMPLATE,
                "hint_string": "multiline",
                "tooltip": "Template for ASS subtitle.",
            }
        },
    },
}
